name: aisect_custom
description: Aisect university.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  badges: ^2.0.3
  animations: ^2.0.2
  cached_network_image: ^3.2.0
  carbon_icons: ^0.0.1+2
  # cashfree_pg: ^2.0.7+27
  cloud_firestore: ^3.1.15
  connectivity_plus: ^2.3.0
  # connectivity: ^3.0.6
  cupertino_icons: ^1.0.4
  delayed_display: ^2.0.0
  dio: ^4.0.0
  file_picker: ^4.5.1
  firebase_app_check: ^0.0.6+7
  firebase_auth: ^3.3.14
  firebase_core: ^1.17.0
  firebase_phone_auth_handler: ^1.0.4
  # pinput: ^2.2.10
  firebase_storage: ^10.2.12
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  flutter_progress_hud: ^2.0.0
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: ^1.0.0

  fluttertoast: ^8.0.9
  form_field_validator: ^1.1.0
  get: ^4.6.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.0
  hive: ^2.0.5
  im_stepper: ^1.0.1+1
  image_picker: ^0.8.5
  intl: ^0.17.0
  lint: ^1.8.2
  local_auth: ^2.0.0
  lottie: ^1.3.0
  open_file: ^3.2.1
  page_view_indicators: ^2.0.0
  path_provider: ^2.0.9
  pdf: ^3.8.1
  permission_handler: ^10.0.0
  provider: ^6.0.2
  razorpay_flutter: ^1.3.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.13
  simple_animations: ^4.0.1
  syncfusion_flutter_pdf: ^20.1.48-beta
  timelines: ^0.1.0
  velocity_x: ^3.4.0
  flutter_native_splash: ^2.2.3+1
  animated_splash_screen: ^1.2.0
  animated_text_kit: ^4.2.1
  timeline_tile: ^2.0.0
  uuid: ^3.0.6
  flutter_facebook_auth: ^4.3.4+2
  paytm_allinonesdk: ^1.1.7
  bottom_navy_bar: ^6.0.0
  # jitsi_meet: ^4.0.0
  jitsi_meet_fix: ^4.0.5
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.1.1+1
  dropdown_button2: ^1.6.3
  flutter_local_notifications: ^9.7.0
  workmanager: ^0.5.0
  #overlay_support: ^2.0.1
  # path_provider_android: ^2.0.12
dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/ic_launcher_round.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/files/courses.json
    - assets/files/idpass.json
    - assets/files/
    - assets/fonts/
    - assets/files/ExamCourse.json
    - assets/animations/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Agne
      fonts:
        - asset: assets/fonts/Agne.ttf

  # - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
