// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnCucncDMWAh74uzC4znPq1zgmmm3DCAQ',
    appId: '1:481443211004:web:8f07c09d19290e302c9979',
    messagingSenderId: '481443211004',
    projectId: 'aisect-42fe7',
    authDomain: 'aisect-42fe7.firebaseapp.com',
    storageBucket: 'aisect-42fe7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK2K_cUdC-Evt93nHbaERwhMbFh7EcIqk',
    appId: '1:481443211004:android:5f5e5a5244514f332c9979',
    messagingSenderId: '481443211004',
    projectId: 'aisect-42fe7',
    androidClientId:
        '481443211004-bfes0arv3srj5u2h3228ij9hf83ss5ad.apps.googleusercontent.com',
    storageBucket: 'aisect-42fe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbRAms80hbSIWTp5g49lDsfbREyY14x0E',
    appId: '1:481443211004:ios:5f15d81361e2a8872c9979',
    messagingSenderId: '481443211004',
    projectId: 'aisect-42fe7',
    storageBucket: 'aisect-42fe7.appspot.com',
    androidClientId:
        '481443211004-bfes0arv3srj5u2h3228ij9hf83ss5ad.apps.googleusercontent.com',
    iosClientId:
        '481443211004-ld666q2l4048q5ca9mup5fdrqh1ire62.apps.googleusercontent.com',
    iosBundleId: 'com.example.aisectCustom',
  );
}
